#!/bin/bash

WF="node_modules/.bin/watch-file"
SOURCES="xstream.js"

echo
echo "Running tests and ./mk..."
echo
./test && ./mk

echo
echo "Watching file $SOURCES"...
echo

while true
do
	$WF $SOURCES
	echo
	echo "Running tests and ./mk..."
	echo
	./test && ./mk
done

