#!/usr/bin/env node
// vim: set ft=javascript:

var repl = require('repl');

console.log('Welcome!');
console.log('This is an interactive shell where you can try out streams.');
console.log('I have taken the liberty to create a few useful variables for you.');
console.log('');
console.log('stream         : require(\'./xstream\')');
console.log('s1             : stream()');
console.log('s2             : stream()');
console.log('s3             : stream.combine(s1, s2, function(a, b) { return [a, b]; })');
console.log('');
console.log('Things to try:');
console.log('');
console.log('s1.update(1);');
console.log('s1.update(2); s2.update(3) // test transactions');
console.log('stream.fromArray([1,2,3,4,5]).log(\'got\')');
console.log('stream.fromString(\'foo\').(\'char \')');
console.log('');

var context = repl.start('> ').context;

context.logPrefix = function(prefix) {
	return function() {
		var args = Array.prototype.slice.call(arguments);
		args.unshift(prefix);
		console.log.apply(console, args);
	};
};

context.log = function() {
	console.log.apply(console, arguments);
};

context.stream = require('./xstream');
context.s1 = context.stream().log('s1');
context.s2 = context.stream().log('s2');
context.s3 = context.stream.combine(
	context.s1, context.s2, function(a, b) { return [a, b]; }).log('s3');

