#!/bin/bash
#
# ./test [ string ] 
#
# Run tests, optionally filtering only those that match string
# If string is 'all' or unspecified, run all tests.
#
# TODO if there's a need to parallelize, do something like
#
#   ./test "2 % 5"     run tests whose idx % 5 == 2
#
# Example:
#
# ./test         run all tests
# ./test 2.7     run tests that match '2.7', e.g. 2.7.1, 2.7.2; also 1.2.7
# ./test end     run tests that match 'end'
# 

cd $(dirname $0)

TESTS=$1
# There's probably a shell way to do this
if [ "$TESTS" == "" ]; then TESTS=all; fi

XSTREAM_TESTS=$TESTS node xstream.js

# Old stuff
#mkdir -p tmp
#SOURCES="README.pre spec/*.pre docs/*.pre"
#./mktest $SOURCES > tmp/test.js
#echo Generated tmp/test.js from $SOURCES
#echo Running tmp/test.js...
#node tmp/test.js

