#!/bin/bash

cd $(dirname $0)

PRETEXT=../node_modules/.bin/pretext

TMPTARGET=/tmp/index-$RANDOM.html
TARGET=index.html

cat pre.html > $TMPTARGET

for file in *.pre
do
	$PRETEXT $file >> $TMPTARGET
done

cat post.html >> $TMPTARGET

mv $TMPTARGET $TARGET
ls -l $TARGET

