#!/bin/bash

cd $(dirname $0)

PRETEXT=../node_modules/.bin/pretext

TMPTARGET=/tmp/index-$RANDOM.html
TARGET=index.html

cat pre.html > $TMPTARGET

$PRETEXT 0-intro.pre >> $TMPTARGET
$PRETEXT 1-errors-ends.pre >> $TMPTARGET
$PRETEXT 2-transactions.pre >> $TMPTARGET

cat post.html >> $TMPTARGET

mv $TMPTARGET $TARGET
ls -l $TARGET

